[project]
name = "uv-dag-dbt-bq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dagster-dbt>=0.26.13",
    "dbt-bigquery>=1.9.1",
]
