name: CICD DBT

on: [push, pull_request]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v0.1.0

      - name: dbt-run
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt run --profiles-dir ."
          dbt_project_folder: "uv_dag_dbt_bq"
        env:
          DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
